### ISSUE TITLE
Don't consider an empty file fatal on start-up

### ISSUE THREAD

**Issue by volter** [logstash-plugins/logstash-filter-translate#16]
I think that having an empty dictionary file should not be fatal. I would consider a situation where there just isn't anything to do at the moment.

**Comment by markwalkom** [comment]
Wouldn't it be better to not include the config section then?

**Comment by volter** [comment]
I'm thinking of a generated file that might be empty in some cases, but filled later on, as it is reloaded every other minute. If memory serves me right, while the file can be empty on a reload, it can not be empty on start-up which appears a bit inconsistent.

**Comment by markwalkom** [comment]
Given there is now dynamic config reloading, it seems like less of an issue to me.

**Comment by mateuszmrozewski** [comment]
With version 3.0.4 empty yaml causes problems. However empty CSV is fine.

**Comment by guyboertje** [comment]
In the near future, in a PR I'm about to create, this is not a problem.
