### ISSUE TITLE
Event dependent dictionary_path

### ISSUE THREAD

**Issue by svetli-n** [logstash-plugins/logstash-filter-translate#18]
Hi and thanks for the nice plugin! 

How about having dependent dictionary_path, for example dictionary_path => "%{host}.yml"

Something similar:
https://github.com/logstash-plugins/logstash-output-file/blob/master/lib/logstash/outputs/file.rb#L83

**Comment by snowdevil17** [comment]
+1,
I have an environment where I need the path to change dependent on time.  The data is not real time, so i need to have a history of dictionaries for bulk historic imports.

**Comment by sethyes** [comment]
Similarly, I have a case where different translations need to be ran depending the source of the event. Therefore, being able to have a ```dictionary_path => "event_translate_%{source}"``` would be extremely useful, rather than having to use case statements like a caveman.

**Comment by jordansissel** [comment]
I think this idea sounds reasonable.

**Comment by wols** [comment]
It would also make my job a lot easier, using the same key several times.
```
# dict_00
A.B.C.D: alias_zero_zero
...
# dict_99.yml
A.B.C.D: alias_nine_nine
...
```
```
if "..." { mutate { replace => { "dict_file" => "dict_01" } } }
else if "..." {  } # and so on
else if "..." { mutate { replace => { "dict_file" => "dict_99" } } }
else "..." { mutate { replace => { "dict_file" => "dict_00" } } }

translate {
    ...
    dictionary_path => "/etc/logstash/dictionary/%{dict_file}.yml"
    ...
}
```

**Comment by guyboertje** [comment]
This idea is not feasible given that the file is loaded when LS starts. I'm also about to add a pull request that changes the dictionary refresh to being async from the filter invocation cadence.

My advice is to use the jdbc_static filter. The parameters setting allows you to build a interpolated key, e.g. `parameters => { "sought" => "%{[host]}-%{[some_id]}" }`
To achieve this you need to have all the different domain rows in one table with a domain + id column to match by.
