### ISSUE TITLE
Issues with Java 9

### ISSUE THREAD

**Issue by zappeee** [logstash-plugins/logstash-filter-translate#20]
When having Java 9 installed instead of 8 I get these error messages:

xxx:/opt/logstash$ sudo bin/plugin install logstash-filter-translate
Java HotSpot(TM) 64-Bit Server VM warning: Option UseParNewGC was deprecated in version 9.0 and will likely be removed in a future release.
Java HotSpot(TM) 64-Bit Server VM warning: Option UseParNewGC was deprecated in version 9.0 and will likely be removed in a future release.
io/console not supported; tty will not be manipulated
OpenSSL::X509::StoreError: setting default path failed: No password supplied for PKCS#12 KeyStore.
  set_default_paths at org/jruby/ext/openssl/X509Store.java:185
             (root) at /opt/logstash/vendor/bundle/jruby/1.9/gems/jruby-openssl-0.9.13-java/lib/jopenssl/load.rb:25
            require at org/jruby/RubyKernel.java:1040
             (root) at /opt/logstash/vendor/jruby/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:1
            require at /opt/logstash/vendor/jruby/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:54
            require at org/jruby/RubyKernel.java:1040
             (root) at /opt/logstash/vendor/bundle/jruby/1.9/gems/jruby-openssl-0.9.13-java/lib/openssl.rb:1
             (root) at /opt/logstash/vendor/jruby/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:1
            require at org/jruby/RubyKernel.java:1040
            require at /opt/logstash/vendor/jruby/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:54
             (root) at /opt/logstash/vendor/jruby/lib/ruby/shared/rubygems/security.rb:11
            require at org/jruby/RubyKernel.java:1040
             (root) at /opt/logstash/vendor/jruby/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:1
            require at /opt/logstash/vendor/jruby/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:54
            require at org/jruby/RubyKernel.java:1040
             (root) at /opt/logstash/vendor/jruby/lib/ruby/shared/rubygems/package.rb:43
             (root) at /opt/logstash/vendor/jruby/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:1

**Comment by jsvd** [comment]
this seems to have [happened before](https://github.com/elastic/logstash/issues/3617) but we haven't fixed logstash w/ java 9 yet

**Comment by zappeee** [comment]
Ah yeah, no need to keep this open.
