### ISSUE TITLE
Add feature to identify object to translate by tag, or add wildcard/regex suppport for field value

### ISSUE THREAD

**Issue by CSUMBmWall** [logstash-plugins/logstash-filter-translate#26]
I have a field with an array of values I need translated. Since translate only works on the first value, I renamed all of the fields dynamically to input_["value"]. Now I can't use translate on them because it requires a specific field, and I have any number of these fields that were once in an array, and are now named according to their value.

If I could use translate on an array, could translate according to a tag, instead of a field, or if I could use a wildcard/regex/pattern for the field value, I would be a happy camper.

**Comment by andrewvc** [comment]
Thanks for the feature suggestion! We have limited time and resources but love approving well written PRs.

Have you considered creating a patch to address this request? We'd love to review it :)

**Comment by CSUMBmWall** [comment]
You're welcome for the suggestion, and appreciation for my situation.  I
can definitely appreciate having limited time and resources.

I don't have much experience with Ruby, or I would jump right in.  I found
the section where it checks for an array, and only translates the first
one.  If I can figure out how to change it, I will send it over for review.

Thanks for the response!

Matt

**Comment by jordansissel** [comment]
@CSUMBmWall you want it to translate the entire array? If so, I like the idea.

**Comment by CSUMBmWall** [comment]
Cool!  I'll hit you up if I can get it done.

**Comment by guyboertje** [comment]
Handling `field` as an array and adding each translation to a `destination` array is not all that hard but in 2.2 years there has not been many 👍 for the feature.

**Comment by guyboertje** [comment]
Closing, this feature was added in #67 with the iterate_on setting. v3.2.0
