### ISSUE TITLE
Allow dictionary_path to consume a csv or other formats for the dictionary file

### ISSUE THREAD

**Issue by geekpete** [logstash-plugins/logstash-filter-translate#29]
Hi Team,

Currently we are restricted to using only YAML file input for the dictionary_path:
https://www.elastic.co/guide/en/logstash/current/plugins-filters-translate.html#plugins-filters-translate-dictionary_path

It would be much more flexible to allow other types of input as the dictionary with the added feature of selecting which columns in the input data to use for key and for value in the dictionary. So a bit more data munging flexibility.

Many people using this feature will probably be trying to use CSV file data for the dictionary and currently those people have to manually convert their data to YAML with a separate tool or script, breaking them out of the logstash tool chain.

A nicer option would be adding flexibility to this plugin in particular around the dictionary feature to allow less clean data inputs for joining purposes, starting with CSV as most common and also allowing extra parameters to specify which fields to use as key and value.

an example might be:

a csv that someone wants to use as a dictionary source:
```
,Name,Prefix,Date Joined,"Date of Last Deposit","Date of Last Query"
20,Green Section,10.17143,,unknown,unknown
21,Blue Section,10.5663,"Mar 24, 2011","Jan 13, 2016",unknown
22,Yellow Department,10.17524,,"Jun 30, 2015",unknown
23,Orange Prefecture,10.18399,,"Dec 16, 2015",unknown
24,Purple Subdivision,10.15413,"May 20, 2014",unknown,unknown
25,Puce Section,10.17994,,"Feb 12, 2016",unknown
27,"Turquoise Section",10.19138,,"Feb 05, 2016",unknown
```

an example YAML dictionary for this data using two required fields, name and prefix:

```
"10.17143": "Green Section"
"10.5663": "Blue Section"
"10.17524": "Yellow Department"
"10.18399": "Orange Prefecture"
"10.15413": "Purple Subdivision"
"10.17994": "Puce Section"
"10.19138": "Turquoise Section"
```

but it would be more awesome to have the translate plugin just use the raw csv file with something like:

```
    translate {
        field => "prefix"                  # target input file to translate
        destination => "departments"    # destination field to put the translated value into
        dictionary_path => "/file/location/target_dict_data.csv"
        dictionary_type => "csv"            # default could be yaml, but others specified here
        dictionary_columns => ["Line Number","Name","Prefix","Date Joined","Date of Last Deposit","Date of Last Query"]          # labels for each column in order
        dictionary_key_field => "Prefix"
        dictionary_value_field => "Name"
    }
```

So you could go down the rabbit hole on this feature, but just being able to get csv data in and pick your columns would be a huge help, but you'd probably also need a way to do some sort of basic validation otherwise people will get caught easily on unclean data and they'll have to revert to using external tools to do pre-cleaning again before import.

Basic validation such as:
- how to handle null/blank fields in the input csv. (use a defined default value when this is hit?)
- how to exclude "bad" data in fields with the option to replace with a default value instead.

**Comment by sslupsky** [comment]
@geekpete It is not documented in the Elastic documentation, but apparently the plugin supports CSV and JSON.  See PR #14

**Comment by geekpete** [comment]
Thanks, I'll test it and fix the docs.

**Comment by untergeek** [comment]
Closing.  Thank you.
