### ISSUE TITLE
Cannot load dictionary_path via docker container volume

### ISSUE THREAD

**Issue by orweinberger** [logstash-plugins/logstash-filter-translate#36]
I'm running Logstash 2.4 with the v3.0.0 of the logstash-filter-translate. I have the following configuration:

```
filter {
  translate {
    dictionary_path => "/config/ip_to_plugin.yml"
    field => "host"
    destination => "plugin"
  }
}
```

In my docker run command, I map the volume `/my-config-dir:/config` which has the `ip_to_plugin.yml` file and it is fully accessible to the logstash process.

However, when I try and launch logstash with the above config I get this error:

```
{:timestamp=>"2016-09-14T10:33:21.593000+0000", :message=>"Pipeline aborted due to error", :exception=>"RuntimeError", :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-translate-3.0.0/lib/logstash/filters/translate.rb:273:in `loading_exception'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-translate-3.0.0/lib/logstash/filters/translate.rb:235:in `load_dictionary'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-translate-3.0.0/lib/logstash/filters/translate.rb:143:in `register'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-translate-3.0.0/lib/logstash/filters/translate.rb:166:in `lock_for_write'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-translate-3.0.0/lib/logstash/filters/translate.rb:143:in `register'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/pipeline.rb:182:in `start_workers'", "org/jruby/RubyArray.java:1613:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/pipeline.rb:182:in `start_workers'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/pipeline.rb:136:in `run'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/agent.rb:491:in `start_pipeline'"], :level=>:error}
```

I guess that the translate plugin tries to 'lock' the file somehow? I'm not sure how to resolve this.

**Comment by jrstear** [comment]
me too - same versions,  no docker.  on ubuntu, installed logstash deb, and translate via logstash-plugin command.  also tried csv, same error.

    Pipeline aborted due to error {:exception=>"RuntimeError", :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-translate-3.0.0/lib/logstash/filters/translate.rb:273:in `loading_exception'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-translate-3.0.0/lib/logstash/filters/translate.rb:235:in `load_dictionary'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-translate-3.0.0/lib/logstash/filters/translate.rb:143:in `register'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-translate-3.0.0/lib/logstash/filters/translate.rb:166:in `lock_for_write'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-translate-3.0.0/lib/logstash/filters/translate.rb:143:in `register'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/pipeline.rb:182:in `start_workers'", "org/jruby/RubyArray.java:1613:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/pipeline.rb:182:in `start_workers'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/pipeline.rb:136:in `run'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/agent.rb:491:in `start_pipeline'"], :level=>:error, :file=>"logstash/agent.rb", :line=>"493", :method=>"start_pipeline"}

**Comment by orweinberger** [comment]
For me, it was a malformed YAML content.
