### ISSUE TITLE
Feature Request - Dictionary from Elasticsearch Terms Filter Lookup

### ISSUE THREAD

**Issue by gferreux** [logstash-plugins/logstash-filter-translate#37]
Is there a way to use an elasticsearch index as a dictionary source ?

Something like this:
filter {
  translate {
    field => "id"
    destinations => ["newField1","newField2"]
    dictionary => {
      type => "elasticsearch_lookup"
      host => "localhost:9200"
      index => "lookups"
      type => "lookupType1"
      key => "_id"
      lookupFields => ["field1Name","field2Name"]
    }
  }
}

and an index like this:
{
        "_index": "lookups",
        "_type": "lookupType1",
        "_id": "id1",
        "_source": {
          "id1": 1,
          "field1Name": "field1Value",
          "field2Name": "field2Value"
}

that would be able to:
- initial field:
  id: id1
- added fields:
  newfField1: field1Value
  newfField2: field2Value

**Comment by elvarb** [comment]
The best way would to be to create a script that would query Elasticsearch and write the results to a dictionary file for the translate filter.

**Comment by guyboertje** [comment]
There is the elasticsearch filter for this.
