### ISSUE TITLE
Bad Syntax in dictionary file - improper

### ISSUE THREAD

**Issue by SecEng** [logstash-plugins/logstash-filter-translate#4]
I believe i have a found a bug in the translate plugin reading of a dictionary file.

It logs the error: 
"LogStash::Filters::Translate: Bad Syntax in dictionary file $filename"

However the file is valid yaml, (verified with syntax checkers, and perl).

To replicate the issue have the file contain:
"myKey": "DON\T"

the value in this case is DON\T, this is obviously improper as there is no \T value, in our case the data wasn't properly sanitized, however other yaml parsers are able to load this and parse it successfully.

Also, the error message does not show the line number or the offending line, it would be very useful for troubleshooting to include that information.

**Comment by jsvd** [comment]
This is a behaviour of the yaml library Ruby uses:

```ruby
 % ruby -ryaml -e "YAML.load('\"myKey\": \"DON\T\"')"
Psych::SyntaxError: (<unknown>): found unknown escape character T(84) while scanning a double-quoted scalar at line 1 column 15
         parse at org/jruby/ext/psych/PsychParser.java:215
...
```

Unless we switch to another parser or sanitize the document in advance there doesn't seem much we can do here.

**Comment by SecEng** [comment]
The interesting part is that neither Perl, or other syntax checkers have this problem.

Oh well, i agree that resolving this isn't worth the trouble. Thanks for looking into it.
