### ISSUE TITLE
Unknown setting 'cidr' for translate

### ISSUE THREAD

**Issue by purplesrl** [logstash-plugins/logstash-filter-translate#46]
```
            translate {
                dictionary_path => "/opt/logstash/config/data/Edge313-Dep-Forli-ip.yaml"
                add_tag => [ "safe_src_ip" ]
                field => "src_ip"
                cidr => true
                exact => true
            }

```
Logstash 5.4.0
plugins installed: logstash-filter-translate, logstash-filter-cidr (did not work without it either)

**Comment by jaredmcqueen** [comment]
cidr is only available using the cidr plugin, you can't use it with translate

**Comment by purplesrl** [comment]
thank you for your answer

i found however a pull that has not been merged:

https://github.com/logstash-plugins/logstash-filter-translate/pull/31

if i compile https://github.com/gandalfb/logstash-filter-translate all seems to work
