### ISSUE TITLE
Translation does not work if source and dest field is the same

### ISSUE THREAD

**Issue by vbohata** [logstash-plugins/logstash-filter-translate#55]
According to documentation setting the same source and dest field should lead to "in-place" replacements. Instead of it, translate do not work (do not translate).
`
      translate {
        exact => false
        field => "severity"
        destination => "severity"
        dictionary => {
          "DBG" => "DEBUG"
          "INF" => "INFO"
          "ERR" => "ERROR"
        }
      }
`

If destination is other field, translation work. For example the values here are translated to severitydest:
`      translate {
        exact => false
        field => "severity"
        destination => "severitydest"
        dictionary => {
          "DBG" => "DEBUG"
          "INF" => "INFO"
          "ERR" => "ERROR"
        }
      }
`

**Comment by guyboertje** [comment]
@vbohata 
Please give the text in the `severity` field of a sample event.

**Comment by guyboertje** [comment]
It does work if you set `"override" => true`. I will update the docs.

Closing.

**Comment by branchnetconsulting** [comment]
I would recommend you mention about the need to use the override option where the idea of overwriting the same field is first brought up in the documentation, here:

https://www.elastic.co/guide/en/logstash/current/plugins-filters-translate.html#plugins-filters-translate-destination

Kevin
