### ISSUE TITLE
"SocketError: recv: name or service not known" while plugin install

### ISSUE THREAD

**Issue by romale** [logstash-plugins/logstash-filter-translate#6]
Hi, after update logstash to 1.5.1 and trying logstash-filter-translate install, i've this error.
It's happen only on an one logstash instance.
Could you help?

/opt/logstash # env|grep proxy
http_proxy=http://localhost:3128
ftp_proxy=http://localhost:3128
gopher_proxy=
https_proxy=http://localhost:3128
no_proxy=localhost, 127.0.0.1

/opt/logstash # sysctl -a|grep ipv6|grep disable
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.eth0.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1

/opt/logstash # DEBUG=1 bin/plugin install logstash-filter-translate
DEBUG: exec /opt/logstash/vendor/jruby/bin/jruby --1.9 -J-XX:+UseParNewGC -J-XX:+UseConcMarkSweepGC -J-Djava.awt.headless=true -J-XX:CMSInitiatingOccupancyFraction=75 -J-XX:+UseCMSInitiatingOccupancyOnly -J-Xmx500m /opt/logstash/lib/pluginmanager/main.rb install logstash-filter-translate
Validating logstash-filter-translate
SocketError: recv: name or service not known
             recv_reply at /opt/logstash/vendor/jruby/lib/ruby/1.9/resolv.rb:782
                request at /opt/logstash/vendor/jruby/lib/ruby/1.9/resolv.rb:664
          each_resource at /opt/logstash/vendor/jruby/lib/ruby/1.9/resolv.rb:512
                 resolv at /opt/logstash/vendor/jruby/lib/ruby/1.9/resolv.rb:0
                   each at org/jruby/RubyArray.java:1613
                 resolv at /opt/logstash/vendor/jruby/lib/ruby/1.9/resolv.rb:1034
                   each at org/jruby/RubyArray.java:1613
                 resolv at /opt/logstash/vendor/jruby/lib/ruby/1.9/resolv.rb:1033
                   each at org/jruby/RubyArray.java:1613
                 resolv at /opt/logstash/vendor/jruby/lib/ruby/1.9/resolv.rb:1031
          each_resource at /opt/logstash/vendor/jruby/lib/ruby/1.9/resolv.rb:503
            getresource at /opt/logstash/vendor/jruby/lib/ruby/1.9/resolv.rb:480
           api_endpoint at /opt/logstash/vendor/jruby/lib/ruby/shared/rubygems/remote_fetcher.rb:92
                api_uri at /opt/logstash/vendor/jruby/lib/ruby/shared/rubygems/source.rb:46
             load_specs at /opt/logstash/vendor/jruby/lib/ruby/shared/rubygems/source.rb:182
             tuples_for at /opt/logstash/vendor/jruby/lib/ruby/shared/rubygems/spec_fetcher.rb:261
        available_specs at /opt/logstash/vendor/jruby/lib/ruby/shared/rubygems/spec_fetcher.rb:226
                   each at org/jruby/RubyArray.java:1613
            each_source at /opt/logstash/vendor/jruby/lib/ruby/shared/rubygems/source_list.rb:97
        available_specs at /opt/logstash/vendor/jruby/lib/ruby/shared/rubygems/spec_fetcher.rb:222
  search_for_dependency at /opt/logstash/vendor/jruby/lib/ruby/shared/rubygems/spec_fetcher.rb:102
    spec_for_dependency at /opt/logstash/vendor/jruby/lib/ruby/shared/rubygems/spec_fetcher.rb:166
       logstash_plugin? at /opt/logstash/lib/pluginmanager/util.rb:20
         verify_remote! at /opt/logstash/lib/pluginmanager/install.rb:48
                   each at org/jruby/RubyArray.java:1613
         verify_remote! at /opt/logstash/lib/pluginmanager/install.rb:46
                execute at /opt/logstash/lib/pluginmanager/install.rb:24
                    run at /opt/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:67
                execute at /opt/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11
                    run at /opt/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:67
                    run at /opt/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:132
                 (root) at /opt/logstash/lib/pluginmanager/main.rb:37

**Comment by purbon** [comment]
Hi @romale, I tested this in a normal situation, having internet connection, no proxies, etc and works as expected. I guess your issues is more related with the your environment and not much with the fact of installing this plugin.

I would like to debug it a bit more, can you provide us with more details about your environment.

* Do you have internet connection in this machine? ipv4 or ipv6?
* Using a proxy? how is this proxy configured?
* OS used?

thanks a lot,

- purbon 

PD: most probably this should have been pointed at the main repo (https://github.com/elastic/logstash) as it looks more like an issue related to the plugin manager, but happy to first sort it out here and then open a more detailed issue there. What do you think?

**Comment by romale** [comment]
Hi @purbon , this machine in LAB segment, with no direct connection to internet. So, i've configured proxy with no auth and my environment is:
- ipv4
- yes, I use proxy (ssh redirection to 3128)
netflow:/opt/logstash # env|grep -i proxy
NO_PROXY=localhost, 127.0.0.1
http_proxy=http://localhost:3128
ftp_proxy=http://localhost:3128
gopher_proxy=
https_proxy=http://localhost:3128
no_proxy=localhost, 127.0.0.1
HTTP_PROXY=http://127.0.0.1:3128
- openSUSE 13.1 (Bottle) (x86_64)

Proxy is working (curl from problem machine):

netflow:/opt/logstash # curl https://github.com/logstash-plugins/logstash-filter-translate/issues/6 | more
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
<!DOCTYPE html>
<html lang="en" class="">
  <head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# object: http://ogp.me/ns/object# article: http://ogp.me/ns/article# profile: http://ogp.me/ns/profile#">
    <meta charset='utf-8'>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="Content-Language" content="en">
    <meta name="viewport" content="width=1020">
    
    
    <title>&quot;SocketError: recv: name or service not known&quot; while plugin install · Issue #6 · logstash-plugins/logstash-filter-translate · GitHub</title>
    <link rel="search" type="application/opensearchdescription+xml" href="/opensearch.xml" title="GitHub">

**Comment by romale** [comment]
Now, I've using logstash-1.5.4, the problem is same

**Comment by purbon** [comment]
@romale your problems are only with translate or also with other plugins? I guess this problems are with every plugin you might try to install. If so it would be nice to move this issue to the main repo. What do you think?

**Comment by romale** [comment]
what's other example plugin can I install? for testing. I'm newbie in ELK

**Comment by purbon** [comment]
@romale check logstash-filter-aggregate for example.

**Comment by romale** [comment]
netflow:/opt/logstash # bin/plugin install logstash-filter-aggregate
Validating logstash-filter-aggregate
SocketError: recv: name or service not known
             recv_reply at /opt/logstash/vendor/jruby/lib/ruby/1.9/resolv.rb:782
                request at /opt/logstash/vendor/jruby/lib/ruby/1.9/resolv.rb:664
          each_resource at /opt/logstash/vendor/jruby/lib/ruby/1.9/resolv.rb:512
                 resolv at /opt/logstash/vendor/jruby/lib/ruby/1.9/resolv.rb:0
                   each at org/jruby/RubyArray.java:1613
                 resolv at /opt/logstash/vendor/jruby/lib/ruby/1.9/resolv.rb:1034
                   each at org/jruby/RubyArray.java:1613
                 resolv at /opt/logstash/vendor/jruby/lib/ruby/1.9/resolv.rb:1033
                   each at org/jruby/RubyArray.java:1613
                 resolv at /opt/logstash/vendor/jruby/lib/ruby/1.9/resolv.rb:1031
          each_resource at /opt/logstash/vendor/jruby/lib/ruby/1.9/resolv.rb:503
            getresource at /opt/logstash/vendor/jruby/lib/ruby/1.9/resolv.rb:480
           api_endpoint at /opt/logstash/vendor/jruby/lib/ruby/shared/rubygems/remote_fetcher.rb:92
                api_uri at /opt/logstash/vendor/jruby/lib/ruby/shared/rubygems/source.rb:46
             load_specs at /opt/logstash/vendor/jruby/lib/ruby/shared/rubygems/source.rb:182
             tuples_for at /opt/logstash/vendor/jruby/lib/ruby/shared/rubygems/spec_fetcher.rb:261
        available_specs at /opt/logstash/vendor/jruby/lib/ruby/shared/rubygems/spec_fetcher.rb:226
                   each at org/jruby/RubyArray.java:1613
            each_source at /opt/logstash/vendor/jruby/lib/ruby/shared/rubygems/source_list.rb:97
        available_specs at /opt/logstash/vendor/jruby/lib/ruby/shared/rubygems/spec_fetcher.rb:222
  search_for_dependency at /opt/logstash/vendor/jruby/lib/ruby/shared/rubygems/spec_fetcher.rb:102
    spec_for_dependency at /opt/logstash/vendor/jruby/lib/ruby/shared/rubygems/spec_fetcher.rb:166
       logstash_plugin? at /opt/logstash/lib/pluginmanager/util.rb:21
         verify_remote! at /opt/logstash/lib/pluginmanager/install.rb:50
                   each at org/jruby/RubyArray.java:1613
         verify_remote! at /opt/logstash/lib/pluginmanager/install.rb:48
                execute at /opt/logstash/lib/pluginmanager/install.rb:26
                    run at /opt/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:67
                execute at /opt/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11
                    run at /opt/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:67
                    run at /opt/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:132
                 (root) at /opt/logstash/lib/pluginmanager/main.rb:37
netflow:/opt/logstash # env|grep -i proxy
NO_PROXY=localhost, 127.0.0.1
http_proxy=http://localhost:3128
ftp_proxy=http://localhost:3128
gopher_proxy=
HTTPS_PROXY=http://127.0.0.1:3128
https_proxy=http://localhost:3128
no_proxy=localhost, 127.0.0.1
HTTP_PROXY=http://127.0.0.1:3128
netflow:/opt/logstash #

**Comment by romale** [comment]
@purbon , how to move to main repo? Or do i need to recreate issue?

**Comment by purbon** [comment]
@romale same error, please reopen this issue at https://github.com/elastic/logstash we should clarify proxsy support for installation. I will investigate after you reopen. Yes you will need to open a new one and link to this.

Thanks a lot for your feedback! much appreciate.

In the meanwhile I propose you can use the last 2.x branch. This include

**Comment by purbon** [comment]
Hit enter too fast, the think I wanted to share if https://www.elastic.co/guide/en/logstash/current/offline-plugins.html, might help in case you can get a place without the proxy to perform the install. I will investigate the proxy situation.

thanks a lot.

**Comment by purbon** [comment]
@romale btw, just wondering is your proxy forwarding ssl properly?. To interact with the plugin repo you use https.
