### ISSUE TITLE
Unable to install logstash-filter-translate.gem plugin

### ISSUE THREAD

**Issue by surajbora007** [logstash-plugins/logstash-filter-translate#64]
Unable to install logstash-filter-translate.gem plugin getting below error.

[root@vm bin]# /usr/share/logstash/bin/logstash-plugin install /usr/share/logstash/plugins/logstash-filter-translate.gem
Validating /usr/share/logstash/plugins/logstash-filter-translate.gem
Installing logstash-filter-translate
fatal: Not a git repository (or any of the parent directories): .git
Error Bundler::HTTPError, retrying 1/10
Could not fetch specs from https://rubygems.org/
Error Bundler::HTTPError, retrying 2/10
Could not fetch specs from https://rubygems.org/
Error Bundler::HTTPError, retrying 3/10
Could not fetch specs from https://rubygems.org/
Error Bundler::HTTPError, retrying 4/10
Could not fetch specs from https://rubygems.org/
Error Bundler::HTTPError, retrying 5/10
Could not fetch specs from https://rubygems.org/
Error Bundler::HTTPError, retrying 6/10
Could not fetch specs from https://rubygems.org/
Error Bundler::HTTPError, retrying 7/10
Could not fetch specs from https://rubygems.org/
Error Bundler::HTTPError, retrying 8/10
Could not fetch specs from https://rubygems.org/
Error Bundler::HTTPError, retrying 9/10
Could not fetch specs from https://rubygems.org/
Error Bundler::HTTPError, retrying 10/10
Could not fetch specs from https://rubygems.org/
Too many retries, aborting, caused by Bundler::HTTPError
ERROR: Installation Aborted, message: Could not fetch specs from https://rubygems.org/
[root@vm bin]#

Version: 6.1.2-1
Operating System: CentOS 7.4
Steps to Reproduce: Execute below command to install the plugin.
/usr/share/logstash/bin/logstash-plugin install /usr/share/logstash/plugins/logstash-filter-translate.gem

Please let me know if I am missing any configuration.

**Comment by guyboertje** [comment]
Does your CentOS machine have access to the internet?
