### ISSUE TITLE
Docs: old doc on web page

### ISSUE THREAD

**Issue by bartekbrzezinski** [logstash-plugins/logstash-filter-translate#78]
[Documentation](https://www.elastic.co/guide/en/logstash/5.6/plugins-filters-translate.html#plugins-filters-translate-dictionary) regarding `dictionary` setting in its example suggests using commas in hash instead of newlines, when separating key - value pairs. (This applies to current version too.) This is very misleading, as top results for "translate" search on Discuss suggest using arrays: e.g. [here](https://discuss.elastic.co/t/mutate-switch-statement/54720/2) and [here](https://discuss.elastic.co/t/add-field-only-if-its-does-not-exists/54894).

Yet, the source asciidoc document displays correct example with hash entries separated by newlines - it was fixed 3 months ago by [this commit](https://github.com/logstash-plugins/logstash-filter-translate/commit/1e056f4f4872eca29307bf05a5b1d3b8fff881d3). Looks like documentation web page was not rendered from GitHub source since then.

**Comment by karenzone** [comment]
You're right! The source is correct, but the docs for current version (6.4) were generated just before version bump was merged.  I'll fix.

**Comment by karenzone** [comment]
Fixed and verified for 6.5 and above
